In [11]:
class SuperKahraman():
    def __init__(self,isimInput,yasInput,meslekInput):
        print("init çağırıldı")
        self.isim = isimInput
        self.yas = yasInput
        self.meslek = meslekInput

In [12]:
superman = SuperKahraman("Superman",30,"Gazeteci")

init çağırıldı


In [13]:
# ben bu süper kahramanlar için özellik girmek istersem bunlara 'attribute' denir.

In [15]:
superman.isim = "batman"

In [16]:
superman.isim

'batman'

In [23]:
class kopek():
    def __init__(self,yas=5):
        self.yas = yas


In [24]:
benimKopek = kopek()

In [25]:
benimKopek.yas

5

In [26]:
# herhangi bir değer verilmese de çalışmaya devam etmesini istiyoruz
# o zaman bunu yapmamız gerekecektir. 

In [27]:
# yas tanımını self içinde yaparsak defualt değer olarak onu gösterir 
# ancek bu değerin istenilen zamanda değiştirilemeyeceği anlamına gelmez 
# değer döndürürken girmek istediğimiz yaşı girersek makine onu döndürür

In [52]:
class kopekler():
    def __init__(self,age):
        self.age = age
        self.peopleAge = self.age* 7
    def bilgi_goster(self):
        print(f"köpeğin yaşı: {self.age} , İnsan yaşı: {self.peopleAge}")

In [53]:
bırıncıKopek = kopekler(4)

In [54]:
bırıncıKopek.bilgi_goster()

köpeğin yaşı: 4 , İnsan yaşı: 28


## İnheritance

In [55]:
class Hayvan():
    def __init__(self):
        print("hayvan sınııfı init çağırıldı")
    def method(self):
        print("hayvan sınıfı methode bir çağırıldı")
    def methode2(self):
        print("hayvan sınıfı methode2 çağırıldı")

In [56]:
benimHayvan = Hayvan()

hayvan sınııfı init çağırıldı


In [57]:
benimHayvan.method()

hayvan sınıfı methode bir çağırıldı


In [58]:
benimHayvan.methode2()

hayvan sınıfı methode2 çağırıldı


In [59]:
class kedi(Hayvan):
    def __init__(self):
        Hayvan.__init__(self)
        print("kedi sınıfı init çağırıldı")

In [61]:
benimKedim = kedi()

hayvan sınııfı init çağırıldı
kedi sınıfı init çağırıldı


In [62]:
benimKedim.method()

hayvan sınıfı methode bir çağırıldı


In [65]:
# Hayvan sınıfını kedi sınıfına kalıntıladık ve artık kedi hayvan sınıfının bilgilerini alabilir
# Ancak kedi sınıfının özellikleri hayvan sınıfı tarafından kullanılamaz.
# Hayvan sınıfında yaptığımız değişiklikler kedi sınıfını da etkiler.
# Eğer hayvan sınıfından alınan bir methodun hayvan sınıfında aynı kalmasını ama kedi sınıfında değişmesini istersem
# kedi sınıfı içerisinde yaynı method isimli bir method oluşturup içeriğini değiştirebilirim.

In [66]:
digerHayvan = Hayvan()

hayvan sınııfı init çağırıldı


## POLYMORPHİSM

In [67]:
# aynı isimde olan methıdların veya fonksiyonların ayrı amaca hismet edebilmesini sağlamak.

In [82]:
class Elma():
    def __init__(self,isim):
        self.isim = isim
    def bilgiVer(self):
        return self.isim + " 50 kaloridir."

In [93]:
class Muz():
    def __init__(self,isim):
        self.isim = isim
    def bilgiVer(self):
            return self.isim + " 70 kaloridir."

In [94]:
elma = Elma("elma")

In [95]:
elma.bilgiVer()

'elma 50 kaloridir.'

In [96]:
muz = Muz("muz")

In [97]:
muz.bilgiVer()

'muz 70 kaloridir.'

## NUMPY Konusu

In [1]:
import numpy as np

In [2]:
benimListem = [1,2,3,4,5,6]

In [3]:
matrixListesi = [[10,20,30],[20,30,40],[40,50,60]]

In [4]:
matrixListesi [1] [0]

20

In [5]:
np.array(matrixListesi)

array([[10, 20, 30],
       [20, 30, 40],
       [40, 50, 60]])

## ARANGE 

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
#arange de verdiğimiz değer aralığında bize bir liste oluşturur.

In [9]:
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
#Sonda versiğimiz değer ile liseye eklenecek değerlerin kaçar artacağını belirleriz.

## LİNSPACE

In [11]:
np.linspace(1,20,5)

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

In [12]:
#linspace, aralarında eşit bir aralık olacak şekilde verdiğimiz değerlerle bir matris oluşturur.

In [13]:
#bunlardan önce zeros ve ones methodları vardı bunlar da verilen matrix değerlerine göre sadece o veya sadece 1 den oluşan matrixler verir.

In [15]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

## RANDOM METHOD

In [20]:
np.random.randint(1,50,5)

array([36, 29, 47, 27, 18])

In [21]:
#random metodu belirlediğimiz aralıkta rast gele olacaak şekilde bir liste oluşturur.

In [22]:
#randint deme nedenimiz ise oluşacak matris değerlerinin türünün int olmasıdır.

## NUMPY DİZİ METHODLARI

In [31]:
yeniDizi = np.random.randint(0,30,25)
yeniDizi

array([ 0, 14,  4, 17, 26,  6, 12,  5, 14,  0, 22, 20,  8, 28, 29,  3,  7,
       20, 19,  0, 15,  1, 12, 17,  6])

In [32]:
yeniDizi.reshape(5,5)

array([[ 0, 14,  4, 17, 26],
       [ 6, 12,  5, 14,  0],
       [22, 20,  8, 28, 29],
       [ 3,  7, 20, 19,  0],
       [15,  1, 12, 17,  6]])

In [33]:
# reshape yapmak istediğimizde dizi eleman sayısının çarpanlarına göre bir değer ile matris yapabiliriz.
#örneğin 10 ise 5,5 bir matris ya da 5,2 olabilir ancak 30 elemanlı bir diziyi 5,5 bölemeyiz.

In [34]:
yeniDizi.max()

29

In [35]:
#max değeri bazen görmek zordur büyük veri setleri ile çalışırken özellikle bu methodlar çok işimize yarar.

In [36]:
yeniDizi.min()

0

In [37]:
yeniDizi.argmax()

14

In [39]:
#en büyük değerin kaçıncı indexte olduğunu bulabiliyorum.
# argmin de aynı işlemi minimum değer için yapar.

## PANDAS SERİES

In [6]:
import pandas as pd
import numpy as np

In [7]:
benimSozluk = {"Saadet": 20, "Zeynep": 24, "Aslı": 30}

In [8]:
type(pd.Series(benimSozluk))

pandas.core.series.Series

In [9]:
pd.Series(benimSozluk)

Saadet    20
Zeynep    24
Aslı      30
dtype: int64

In [10]:
yaslar = [20,30,40]
ısımler = ["Saadet","Zeynep","Aslı"]

In [11]:
pd.Series(yaslar)

0    20
1    30
2    40
dtype: int64

In [12]:
pd.Series(yaslar,ısımler)

Saadet    20
Zeynep    30
Aslı      40
dtype: int64

In [13]:
pd.Series(data = yaslar, index = ısımler)

Saadet    20
Zeynep    30
Aslı      40
dtype: int64

In [14]:
numpyDizi = np.array([50,40,30])
numpyDizi

array([50, 40, 30])

In [15]:
pd.Series(numpyDizi)

0    50
1    40
2    30
dtype: int32

In [16]:
pd.Series(["Saadet","Zeynep","Aslı"]),[1,2,3]

(0    Saadet
 1    Zeynep
 2      Aslı
 dtype: object,
 [1, 2, 3])

## DATAFRAME

In [17]:
data = np.random.randn(4,3)

In [18]:
data

array([[-0.60705571, -1.81196509,  0.01170398],
       [ 1.40346959,  0.15950401,  2.73686842],
       [-0.811335  ,  0.26380097,  0.98034908],
       [-0.70227973, -0.85466669,  0.04423462]])

In [19]:
dataFrame = pd.DataFrame(data)

In [20]:
dataFrame[0] #ilk kolonu getirir.

0   -0.607056
1    1.403470
2   -0.811335
3   -0.702280
Name: 0, dtype: float64

In [21]:
yeniDataFrame = pd.yeniDataFrame = pd.DataFrame(data,index = ["Seri 1","Seri 2","Seri 3","Seri 4"],columns = ["kolon 1","kolon 2","kolon 3"])
yeniDataFrame

kolon 1   kolon 2   kolon 3
Seri 1 -0.607056 -1.811965  0.011704
Seri 2  1.403470  0.159504  2.736868
Seri 3 -0.811335  0.263801  0.980349
Seri 4 -0.702280 -0.854667  0.044235

In [22]:
yeniDataFrame["kolon 2"] # kolon çağırmak için de bu kod bloğunu kullanırım.

Seri 1   -1.811965
Seri 2    0.159504
Seri 3    0.263801
Seri 4   -0.854667
Name: kolon 2, dtype: float64

In [23]:
yeniDataFrame[["kolon 1","kolon 2"]] # birden fazla kolon çağırmak istediğimde liste içi liste olarak yazarım.

kolon 1   kolon 2
Seri 1 -0.607056 -1.811965
Seri 2  1.403470  0.159504
Seri 3 -0.811335  0.263801
Seri 4 -0.702280 -0.854667

In [24]:
yeniDataFrame

kolon 1   kolon 2   kolon 3
Seri 1 -0.607056 -1.811965  0.011704
Seri 2  1.403470  0.159504  2.736868
Seri 3 -0.811335  0.263801  0.980349
Seri 4 -0.702280 -0.854667  0.044235

In [25]:
# yeniDataFrame["seri 1"] dersek hata alırız

In [26]:
yeniDataFrame.loc["Seri 3"] # böyle yaparak seri için tüm kolonları döndürmüş oluruz.

kolon 1   -0.811335
kolon 2    0.263801
kolon 3    0.980349
Name: Seri 3, dtype: float64

In [27]:
yeniDataFrame.iloc[2] # iloc methodu ise bu işlemi index numarasına göre yapar.

kolon 1   -0.811335
kolon 2    0.263801
kolon 3    0.980349
Name: Seri 3, dtype: float64

In [28]:
yeniDataFrame

kolon 1   kolon 2   kolon 3
Seri 1 -0.607056 -1.811965  0.011704
Seri 2  1.403470  0.159504  2.736868
Seri 3 -0.811335  0.263801  0.980349
Seri 4 -0.702280 -0.854667  0.044235

In [30]:
yeniDataFrame ["emeklilik yası"] = yeniDataFrame["kolon 1"] + yeniDataFrame["kolon 2"]
yeniDataFrame

kolon 1   kolon 2   kolon 3  emeklilik yası
Seri 1 -0.607056 -1.811965  0.011704       -2.419021
Seri 2  1.403470  0.159504  2.736868        1.562974
Seri 3 -0.811335  0.263801  0.980349       -0.547534
Seri 4 -0.702280 -0.854667  0.044235       -1.556946

In [31]:
# Böyle yaparak tabloma yeni bir kolon ekleyebilirim

In [33]:
yeniDataFrame.drop("emeklilik yası",axis = 1)

kolon 1   kolon 2   kolon 3
Seri 1 -0.607056 -1.811965  0.011704
Seri 2  1.403470  0.159504  2.736868
Seri 3 -0.811335  0.263801  0.980349
Seri 4 -0.702280 -0.854667  0.044235

In [34]:
# Kolon için axis = 1 kullanılırken row için axis = 0 olacaktır.

In [35]:
yeniDataFrame.drop("emeklilik yası", axis = 1, inplace = True)
yeniDataFrame

kolon 1   kolon 2   kolon 3
Seri 1 -0.607056 -1.811965  0.011704
Seri 2  1.403470  0.159504  2.736868
Seri 3 -0.811335  0.263801  0.980349
Seri 4 -0.702280 -0.854667  0.044235

In [36]:
#kalıcı olarak silmek istersem inplace = true derim.

In [38]:
yeniDataFrame.loc["Seri 3", "kolon 2"]

0.26380097037657224

In [39]:
# Böylelilkle de tablo içince ulaşmak istediğim değere kolaylıkla ulaşabilirim.

In [40]:
yeniDataFrame

kolon 1   kolon 2   kolon 3
Seri 1 -0.607056 -1.811965  0.011704
Seri 2  1.403470  0.159504  2.736868
Seri 3 -0.811335  0.263801  0.980349
Seri 4 -0.702280 -0.854667  0.044235

In [41]:
yeniDataFrame.reset_index()

index   kolon 1   kolon 2   kolon 3
0  Seri 1 -0.607056 -1.811965  0.011704
1  Seri 2  1.403470  0.159504  2.736868
2  Seri 3 -0.811335  0.263801  0.980349
3  Seri 4 -0.702280 -0.854667  0.044235

In [42]:
# bunu diyerek index değerlerini görebiliriz.

In [59]:
ilkIndex = ["Simpson","Simpson","Simpson","South park","South park","South park"]

In [60]:
icIndex = ["Homer","Bartmen","Marge","Cartmen","Kenny","Kyle"]

In [61]:
birlesikIndex = list(zip(ilkIndex,icIndex))

In [62]:
birlesikIndex

[('Simpson', 'Homer'),
 ('Simpson', 'Bartmen'),
 ('Simpson', 'Marge'),
 ('South park', 'Cartmen'),
 ('South park', 'Kenny'),
 ('South park', 'Kyle')]

In [63]:
birlesikIndex = pd.MultiIndex.from_tuples(birlesikIndex)

In [64]:
birlesikIndex

MultiIndex([(   'Simpson',   'Homer'),
            (   'Simpson', 'Bartmen'),
            (   'Simpson',   'Marge'),
            ('South park', 'Cartmen'),
            ('South park',   'Kenny'),
            ('South park',    'Kyle')],
           )

In [65]:
cizgiFilm = [[40,"A"],[30,"B"],[20,"C"],[9,"D"],[10,"E"],[12,"F"]]
cizgiFilm

[[40, 'A'], [30, 'B'], [20, 'C'], [9, 'D'], [10, 'E'], [12, 'F']]

In [66]:
cizgiFilmNumpy = np.array(cizgiFilm)

In [67]:
cizgiFilmDataFrame = pd.DataFrame(cizgiFilmNumpy,index = birlesikIndex,columns = ["Yas","Meslek"] )

In [70]:
cizgiFilmDataFrame

Yas Meslek
Simpson    Homer    40      A
           Bartmen  30      B
           Marge    20      C
South park Cartmen   9      D
           Kenny    10      E
           Kyle     12      F

In [69]:
cizgiFilmDataFrame.loc["Simpson"]

Yas Meslek
Homer    40      A
Bartmen  30      B
Marge    20      C

In [71]:
cizgiFilmDataFrame.loc["South park"]

Yas Meslek
Cartmen   9      D
Kenny    10      E
Kyle     12      F

## Eksik Veriler

In [73]:
havaDurumuDataFrame = pd.DataFrame({"İstanbul": [30,29,np.nan],"Ankara": [26,np.nan,25],"İzmir": [30,40,35]})

In [74]:
havaDurumuDataFrame

İstanbul  Ankara  İzmir
0      30.0    26.0     30
1      29.0     NaN     40
2       NaN    25.0     35

In [75]:
havaDurumuDataFrame.dropna()

İstanbul  Ankara  İzmir
0      30.0    26.0     30

In [76]:
# boş değer olan row tamamen çıkarılıyor.

In [78]:
 havaDurumuDataFrame.dropna(axis = 1) # dediğim zaman içinde boş değer olmayan kolon döner

İzmir
0     30
1     40
2     35

In [81]:
yeniDf = pd.DataFrame({"İstanbul": [30,29,np.nan],"Ankara": [26,np.nan,25],"İzmir": [30,40,35],"Antalya": [45,np.nan,np.nan]})
yeniDf = pd.DataFrame(yeniDf)

In [82]:
yeniDf

İstanbul  Ankara  İzmir  Antalya
0      30.0    26.0     30     45.0
1      29.0     NaN     40      NaN
2       NaN    25.0     35      NaN

In [84]:
yeniDf.dropna(axis = 1 ,thresh=2) #thresh dediğim zaman 2 nan değer olanları atar sadece tek nan değer olanları döndürür

İstanbul  Ankara  İzmir
0      30.0    26.0     30
1      29.0     NaN     40
2       NaN    25.0     35

In [85]:
yeniDf.fillna(28)

İstanbul  Ankara  İzmir  Antalya
0      30.0    26.0     30     45.0
1      29.0    28.0     40     28.0
2      28.0    25.0     35     28.0

In [86]:
#Bu kod bloğu ile nan değer olan veriler için elimle bir değer girmiş olurum.

## Groupby

In [6]:
import numpy as np
import pandas as pd

In [18]:
maasSozluk = {"Departmanlar": ["Veri Bilimi","Veri Bilimi","Pazarlama","Pazarlama","Yazılım","Yazılım"],
             "Çalışan İsmi": ["Ahmet","Saadet","Zeynep","Fatih","Eren","Yaşar"],
              "Maas":[100000,2000000,250000,300000,400000,450000]}

In [19]:
maasDataFrame = pd.DataFrame(maasSozluk)
maasDataFrame

Departmanlar Çalışan İsmi     Maas
0  Veri Bilimi        Ahmet   100000
1  Veri Bilimi       Saadet  2000000
2    Pazarlama       Zeynep   250000
3    Pazarlama        Fatih   300000
4      Yazılım         Eren   400000
5      Yazılım        Yaşar   450000

In [23]:
gruplanmısTablo = maasDataFrame.groupby("Departmanlar")
gruplanmısTablo.count()

Çalışan İsmi  Maas
Departmanlar                    
Pazarlama                2     2
Veri Bilimi              2     2
Yazılım                  2     2

In [33]:
gruplanmısTablo.mean("Maas")

Maas
Departmanlar           
Pazarlama      275000.0
Veri Bilimi   1050000.0
Yazılım        425000.0

In [34]:
gruplanmısTablo.min()

Çalışan İsmi    Maas
Departmanlar                     
Pazarlama           Fatih  250000
Veri Bilimi         Ahmet  100000
Yazılım              Eren  400000

In [35]:
gruplanmısTablo.max()

Çalışan İsmi     Maas
Departmanlar                      
Pazarlama          Zeynep   300000
Veri Bilimi        Saadet  2000000
Yazılım             Yaşar   450000

In [36]:
gruplanmısTablo.describe()

Maas                                                          \
             count       mean           std       min       25%        50%   
Departmanlar                                                                 
Pazarlama      2.0   275000.0  3.535534e+04  250000.0  262500.0   275000.0   
Veri Bilimi    2.0  1050000.0  1.343503e+06  100000.0  575000.0  1050000.0   
Yazılım        2.0   425000.0  3.535534e+04  400000.0  412500.0   425000.0   

                                    
                    75%        max  
Departmanlar                        
Pazarlama      287500.0   300000.0  
Veri Bilimi   1525000.0  2000000.0  
Yazılım        437500.0   450000.0